bentabenta/accounts/urls.py
from django.contrib.auth.views import LogoutView 
from django.urls import path ,reverse
from .views import login_page,register_page,guest_login_page

app_name = 'accounts'
urlpatterns = [
    
    path('login/',login_page,name = 'login-page'),
    path('register/',register_page,name = 'register-page'),
    path('logout/',LogoutView.as_view(),name='logout'), #Logout 
    path('register/guest/',guest_login_page, name='register-guest')
]

bentabenta/addresses/urls.py
from django.urls import path
from .views import checkout_address_create_view
app_name ='addresses'
urlpatterns = [
    path('addresses/create/', checkout_address_create_view, name='address-create'),
]

bentabenta/bentabenta/urls.py
from django.conf import settings # check the documentation - this is manually added
from django.conf.urls.static import static # check the documentation - this is manually added


from django.contrib import admin
from django.urls import path ,include

from products.views import (
  #  product_list_view,
 #   product_create_view,
 #   product_detail_view,
 #   product_delete_view,
 #   product_update_view,
    ProductFeaturedListView,
    ProductFeaturedDetailView,
    ProductDetailView)

from pages.views import home_view, contact_page_view
#from cart.views import cart_view,cart_home_view


urlpatterns = [
    path('',include('products.urls',namespace='products')),
    path('',include('pages.urls')),
    path('',home_view,name='home-view'),
    path('',include('cart.urls',namespace = 'cart')),
    path('',include('accounts.urls',namespace='accounts')),
    path('',include('addresses.urls',namespace='addresses')),
    path('admin/', admin.site.urls),
    path('product/<int:id>/',ProductDetailView.as_view() , name ='product-list'),
    path('featured/', ProductFeaturedListView.as_view(), name ='featured-list'),
    path('featured/<int:pid>' ,ProductFeaturedDetailView.as_view(),name ='featured-detail'),

    path('', include('search.urls',namespace='search')),
    
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

bentabenta/cart/urls.py
from django.urls import path,reverse   
from .views import cart_view,cart_home_view ,cart_update,checkout_home,checkout_success_view

app_name='cart'
urlpatterns=[
 #   path('cart/',cart_home_view,name='cart'),
   path('cart/',cart_home_view ,name = 'cart-home'),
   path('cart/update/',cart_update,name = 'cart-update'),
   path('checkout/',checkout_home , name = 'checkout'),    
   path('checkout/success',checkout_success_view,name='checkout-success'),
]

bentabenta/cart/models.py
from decimal import Decimal
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save, post_save, m2m_changed
from products.models import Products
User = settings.AUTH_USER_MODEL

class CartManager(models.Manager):
 #   def get_or_create():
  #      return obj,True

    def new_or_get(self, request):
        cart_id = request.session.get("cart_id" , None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            #print("cart id exist")
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            request_user = request.user
            cart_obj = Cart.objects.new_cart(user=request_user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj,new_obj

    def new_cart(self, user=None):
        user_obj=None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user=user_obj)




# Create your models here.
class Cart(models.Model):
    user        = models.ForeignKey(User,null=True, blank=True,on_delete=models.DO_NOTHING)
    products    = models.ManyToManyField(Products,blank=True)
    subtotal    = models.DecimalField(default=0.00, max_digits=65, decimal_places=2)
    total       = models.DecimalField(default=0,max_digits=65, decimal_places=2)
    updated     = models.DateTimeField(auto_now=True)
    timestamp   = models.DateTimeField(auto_now_add=True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)


class CartItem(models.Model):
    cart        = models.ForeignKey(Cart, on_delete=models.CASCADE)
    products    = models.ForeignKey(Products, blank=True,on_delete=models.CASCADE)
    quantity    = models.IntegerField(default=1)

    def __str__(self):
        return str(self.id)


def m2m_changed_cart_receiver(sender, instance, action,*args, **kwargs):
    if action == 'post_add' or action == 'post_remove':
        products = instance.products.all()
        total = 0
        for x in products:
            total += x.price
        if instance.subtotal != total:
            instance.subtotal = total
            instance.save() 
m2m_changed.connect(m2m_changed_cart_receiver, sender = Cart.products.through)


def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal > 0:
        instance.total = Decimal(instance.subtotal) + Decimal(10)
    else:
        instance.total = 0.00

pre_save.connect(pre_save_cart_receiver, sender = Cart)

bentabenta/cart/views.py
from django.shortcuts import render,redirect
from accounts.forms import LoginForm, GuestForm
from addresses.forms import AddressForm

from accounts.models import GuestEmail
from billings.models import BillingProfile
from addresses.models import Address
from products.models import Products
from orders.models import Order
from .models import Cart,CartItem


# Create your views here.
def cart_view(request):
    
    #print(request.session)
    context={

    }
    return render(request,'cart/cart_list.html',context)

def cart_create(user=None):
    cart_obj = Cart.objects.create(user=None)
    print("New cart created")
    return cart_obj


def cart_home_view(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    cart_product_qty    = CartItem.objects.filter(cart = cart_obj )
    context = {
        "cart":cart_obj,
        "qty"  : cart_product_qty
        } 
    return render(request, 'cart/home.html',context )
    
def cart_update(request):
    product_id = request.POST.get('product_id')
    qty =1
    if product_id is not None:
        try:
            product_obj = Products.objects.get(id=product_id)
        except Products.DoesNotExist:
            print("No Product")
            return redirect("cart:cart-home")
        cart_obj, new_obj = Cart.objects.new_or_get(request)
        if product_obj in cart_obj.products.all():
            cart_obj.products.remove(product_obj)
            CartItem.objects.filter(products=product_obj).delete()
        else:
        #obj = Products.objects.get(id=1)
            cart_obj.products.add(product_obj)
            cartitem_add = CartItem.objects.create(cart=cart_obj, products=product_obj ,quantity=qty) 
        #cart_obj.products.remove()
        request.session['cart_items'] = cart_obj.products.count()
        return redirect("cart:cart-home")


def checkout_home(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None
    product_count = cart_obj.products.count()
    if cart_created  or product_count == 0:
        return redirect("cart:cart-home")
    login_form      =   LoginForm()
    guest_form      =   GuestForm()
    address_form    =   AddressForm()
    #billing_address_form =  AddressForm()
    billing_address_id = request.session.get("billing_address_id", None)
    shipping_address_id = request.session.get("shipping_address_id", None)
    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
    address_qs = None
    if billing_profile is not None:
        if request.user.is_authenticated:
            address_qs = Address.objects.filter(billing_profile=billing_profile)
        #models Manager
        order_obj, order_obj_created = Order.objects.new_or_get(billing_profile ,cart_obj)
        if shipping_address_id:
            order_obj.shipping_address = Address.objects.get(id=shipping_address_id)
            del request.session['shipping_address_id']
        elif billing_address_id:
            order_obj.billing_address = Address.objects.get(id=billing_address_id)  
            del request.session["billing_address_id"]
        if billing_address_id or shipping_address_id:
            order_obj.save()
       # has_card = billing_profile.has_card
    
    if request.method == "POST":
        is_prepared = order_obj.check_done()
        if is_prepared:
            order_obj.mark_paid() # sort a signal for us
            request.session['cart_items'] = 0
            del request.session['cart_id']
            return redirect("cart:checkout-success")
        else:
 
            return redirect("cart:checkout")

    context =   {
        "object" : order_obj,
        "billing_profile" : billing_profile,
        "login_form"    : login_form,
        "guest_form"    : guest_form,
        'address_form'  : address_form,
        "address_qs"    : address_qs,
    } 
    return render(request, "cart/checkout.html" , context)


def checkout_success_view(request):
    return render(request,'cart/checkout_done.html',{})

bentabenta/cart/templates/cart/cart_list.html
{% load static %}
{% extends "base.html" %}
{% block content %}
{% for item in obj %}
{{item}}
{% endfor %}



{% endblock  %}

bentabenta/cart/templates/cart/checkout.html
{% extends "base.html" %}

{% block content %}
{{object.order_id}}
{% if not billing_profile %}
<div class="row">
            <div class="col-12 col-md-6">
                <p>Login</p>
                  {% url 'accounts:login-page' as user_login %}

                {% include "accounts/snippets/form.html" with form=login_form action_url=user_login next_url=request.build_absolute_uri %}
            </div>
                
</div>
              <p style="margin:20px;"></p>

           <div class="row">
                  <div class="col-12 col-md-6 ">
                      <h5>Continue as Guest<h5>
                      {% url 'accounts:register-guest' as guest_register %}
                    
                      {% include "accounts/snippets/form.html" with form=guest_form action_url=guest_register next_url=request.build_absolute_uri %}
                  </div>
              </div>
{% else %}

            {% if not object.shipping_address %}
            {% url 'addresses:address-create' as checkout_address_create%}
            shipping
            {% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='shipping' %}'
            {% elif object.shipping_address and not object.billing_address %}
            {% url 'addresses:address-create' as checkout_address_create%}
            billing
            {% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='billing' %}
            {% else %}
                  <p>Checkout</p>
                  <p>Cart Total : {{object.cart.total}}</p>
                  <p>Billing Profile : {{billing_profile.default_card}}</p>
                  <p>Shipping Total : {{object.shipping_total}}
                  <p>Order Total : {{object.total}}
                    <form method="POST" action=""> {% csrf_token %}
                  <button class="btn btn-primary" type="submit">
                           Submit
                  </button>
            </form>
           


            {% endif %}
{% endif %}
{% endblock  %}

bentabenta/cart/templates/cart/checkout_done.html
{% extends "base.html" %}

{% block content %}

{% endblock %}

bentabenta/cart/templates/cart/home.html
{% extends 'base.html' %}
{% block content %}

Cart
{% if cart.products.exists %}




<table class="table">
  <thead>
    <tr>
      <th scope="col">Quantity</th>
      <th scope="col">Product Name</th>
      <th scope="col">Product Price</th>
      <th scope="col"></th>
    </tr>
  </thead>
  {% for product in cart.products.all %}
  
 
  <tbody>
    <tr>
          <td>
      {% for item in qty %}
      {% if item.products == product %}
      <input type="text" value="{{item.quantity}}"> 
      {% else %}
      {% endif %}
       
  
      {% endfor %}
      </td>
    <!--  <th scope="row">{{ forloop.counter }}</th>-->
      <td><a href="{{ product.get_absolute_url}}">{{ product.name }}</a> <a href=""><small>{% include 'products/snippets/update_cart.html' with product=product cart=cart in_cart=True %}</small></a></td>
      <td>{{ product.price }}</td>

    </tr>
     {% endfor %}
    <tr>
      <th colspan="2"></th>
      <td>Subtotal : <b>{{cart.subtotal}}</b></td>
    </tr>
    <tr>
      <th  colspan="2"></th>
      <td>Total : {{cart.total}}</td>
      <td><a name="" id="" class="btn btn-success" href="{% url 'cart:checkout' %}" role="button">Checkout</a></td>
    </tr>
  </tbody>
</table>
{% else %}
<p class='lead'> Cart is empty</p>
{% endif %}
{% endblock  %}